version: '3.9'

services:

  frontend:
    container_name: frontend
    image: ghcr.io/gjs2162/sample-fullstack-application-frontend:latest
    ports:
      - 3001:3000
    environment:
      - NEXT_PUBLIC_BACKEND_BASE_URL=http://localhost:3000
    restart: always
    depends_on:
      - backend

  backend:
    container_name: backend
    image: ghcr.io/gjs2162/sample-fullstack-application-backend:latest
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    command: >
      sh -c "npx prisma migrate dev --name init && yarn run start"

  db:
    container_name: db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379

volumes:
  pgdata: {}
